import Head from "next/head";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Button from "../components/button";
import Image from "next/image";
import { Typewriter } from "react-simple-typewriter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jexpe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className={styles.hero}>
          <div>
            <h1 className={styles.heading}>
              Easily work with <br />
              <span>
                <span style={{ visibility: "hidden" }}>W</span>
                <Typewriter
                  words={[
                    "Amazon S3",
                    "Azure",
                    "OpenStack",
                    "Backblaze B2",
                    "OneDrive",
                    "Google Drive",
                    "Dropbox",
                    "SSH",
                    "SFTP",
                    "Telnet",
                  ]}
                  loop={0}
                  cursor={false}
                  typeSpeed={150}
                  deleteSpeed={75}
                  delaySpeed={2000}
                />
                <span style={{ visibility: "hidden" }}>W</span>
              </span>
            </h1>
            <h2 className={styles.subheading}>
              Manage multiple servers from one easy-to use interface and share
              credentials between teammates.
            </h2>
            <div style={{ textAlign: "center" }}>
              <Button
                style={{ width: "248px", height: "64px", fontSize: "20px" }}
              >
                Subscribe beta
              </Button>
            </div>
          </div>
        </div>
        <div className={styles.showcase}>
          <div className={styles.softwareShowcase}>
            <Image src="/mac_jexpe.png" width={447} height={352} />
          </div>
          <div className={styles.separator}></div>
          <div
            className={styles.contentArea}
            style={{ backgroundColor: "var(--white)" }}
          >
            <div className={styles.container}>
              <div>
                <h1 className={styles.heading}>
                  <span>All common protocols</span>
                </h1>
                <p className={styles.blackTextContent}>
                  Jexpe is a powerful software package for opening and managing
                  servers. It currently supports: SSH, Telnet, FTP, SFTP,
                  WebDAV, Amazon S3, OpenStack Swift, Backblaze B2, Microsoft
                  Azure, OneDrive, Google Drive and Dropbox.
                </p>
              </div>
              <div>
                <Image src="/protocols.png" width={440} height={420} />
              </div>
            </div>
          </div>
          <div className={styles.contentArea}>
            <div className={styles.container} style={{gridTemplateColumns: "40% 60%"}}>
              <div>
                <Image src="/teams.png" width={440} height={420} />
              </div>
              <div>
                <h1 className={styles.heading}>
                  <span>Work with your team</span>
                </h1>
                <p className={styles.whiteTextContent}>
                  We enable teams to collaboratively manage access of your
                  company servers and credentials, making it easy for you to
                  share these with members of the team. Setting up Jexpe only
                  takes minutes and once activated you can monitor in real time
                  which sharing permissions each staff member has in place
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
