import Head from "next/head";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Button from "../components/button";
import { Typewriter } from "react-simple-typewriter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className={styles.hero}>
          <div>
            <h1 className={styles.heading}>
              Easily work with <br />
              <span>
                <span style={{ visibility: "hidden" }}>W</span>
                <Typewriter
                  words={[
                    "Amazon S3",
                    "Azure",
                    "OpenStack",
                    "Backblaze B2",
                    "OneDrive",
                    "Google Drive",
                    "Dropbox",
                    "SSH",
                    "SFTP",
                    "Telnet",
                  ]}
                  loop={0}
                  cursor={false}
                  typeSpeed={150}
                  deleteSpeed={75}
                  delaySpeed={2000}
                />
                <span style={{ visibility: "hidden" }}>W</span>
              </span>
            </h1>
            <h2 className={styles.subheading}>
              Manage multiple servers from one easy-to use interface and share
              credentials between teammates.
            </h2>
            <div style={{ textAlign: "center" }}>
              <Button
                style={{ width: "248px", height: "64px", fontSize: "20px" }}
              >
                Subscribe beta
              </Button>
            </div>
          </div>
        </div>
        <div className={styles.showcase}>
          <div className={styles.separator}></div>
          <div className={styles.showcaseContent}></div>
        </div>
      </main>
    </>
  );
}
